tap "1password/tap"
tap "bigwig-club/brew"
tap "buo/cask-upgrade"
tap "cloudflare/cloudflare"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
# Shell extension to jump to frequently used directories
brew "autojump"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# View disk space usage and delete unwanted data, fast
brew "dua-cli"
# Fast and simple Node.js version manager
brew "fnm"
# Distributed revision control system
brew "git"
# Development kit for the Java programming language
brew "openjdk"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# User interface to the TELNET protocol
brew "telnet"
# Programmatically correct mistyped console commands
brew "thefuck"
# Internet file retriever
brew "wget"
# Command-line helper for the 1Password password manager
cask "1password-cli"
cask "account-switcher"
# Transfer files from and to an Android smartphone
cask "android-file-transfer"
# Android SDK component
cask "android-platform-tools"
# Application uninstaller
cask "appcleaner"
# Tool to flash OS images to SD cards & USB drives
cask "balenaetcher"
# Tool to list all active shortcuts of the current application
cask "cheatsheet"
# Rule-based custom proxy with GUI based on clash
cask "clashx-pro"
# Voice and text chat software
cask "discord"
# Typeface made for developers
cask "font-jetbrains-mono"
# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"
# GIT client
cask "fork"
# Tool to set light or dark appearance on a per-app basis
cask "gray"
# Free and open-source media player
cask "iina"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# File archiver
cask "keka"
# Helper application for the Keka file archiver
cask "kekaexternalhelper"
# Switch input method per application
cask "keyboardholder"
# Open-source firewall to block unknown outgoing connections
cask "lulu"
# Simple and elegant markdown editor
cask "mark-text"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Smooths scrolling and set mouse scroll directions independently
cask "mos"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# App to write, plan, collaborate, and get organized
cask "notion"
cask "paper"
# Tool for uploading images
cask "picgo"
# QuickLook plug-in that renders source code with syntax highlighting
cask "qlcolorcode"
# Display image info and preview unsupported formats in QuickLook
cask "qlimagesize"
# QuickLook generator for Markdown files
cask "qlmarkdown"
# QuickLook plugin for plaintext files without an extension
cask "qlstephen"
cask "qlvideo"
# QuickLook plugin for JSON files
cask "quicklook-json"
# QuickLook generator for Adobe Swatch Exchange files
cask "quicklookase"
# Control your tools with a few keystrokes
cask "raycast"
# Tool to reverse the direction of scrolling
cask "scroll-reverser"
# Screenshot measurement and annotation tool
cask "shottr"
# Snip or pin screenshots
cask "snipaste"
# Music streaming service
cask "spotify"
# Network toolbox
cask "surge"
# App to switch hosts
cask "switchhosts"
# Terminal emulator, SSH and serial client
cask "tabby"
# Messaging app with a focus on speed and security
cask "telegram"
# Finder extension for opening a terminal from the current directory
cask "termhere"
# General-purpose text editor
cask "textmate"
# Remote desktop application focusing on security
cask "vnc-viewer"
# Rust-based terminal
cask "warp"
cask "webpquicklook"
# Third-party NetEase cloud player
cask "yesplaymusic"
