tap "1password/tap"
tap "alienator88/cask"
tap "beeftornado/rmtree"
tap "bigwig-club/brew"
tap "buo/cask-upgrade"
tap "cloudflare/cloudflare"
tap "felixkratz/formulae"
tap "github/gh"
tap "he3-app/he3"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "lihaoyun6/tap"
tap "mac-cleanup/mac-cleanup-py"
tap "mediar-ai/screenpipe", "https://github.com/mediar-ai/screenpipe.git"
tap "mrkai77/cask"
tap "shaunsingh/sfmono-nerd-font-ligaturized"
tap "th-ch/youtube-music"
# Interpreted, interactive, object-oriented programming language
brew "python@3.11"
# Shell extension to jump to frequently used directories
brew "autojump"
# Cross-platform make
brew "cmake"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Pack, ship and run any application as a lightweight container
brew "docker"
# View disk space usage and delete unwanted data, fast
brew "dua-cli"
# International domain name library (IDNA2008, Punycode and TR46)
brew "libidn2"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Fast and simple Node.js version manager
brew "fnm"
# Distributed revision control system
brew "git"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Update of iperf: measures TCP, UDP, and SCTP bandwidth
brew "iperf3"
# Lightweight and flexible command-line JSON processor
brew "jq"
# Mac App Store command-line interface
brew "mas"
# Open source visual route tracking CLI tool
brew "nexttrace"
# Development kit for the Java programming language
brew "openjdk"
# Fast, disk space efficient package manager
brew "pnpm"
# Protocol buffers (Google's data interchange format)
brew "protobuf"
# Python version management
brew "pyenv"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Safe, concurrent, practical language
brew "rust"
# Display and control your Android device
brew "scrcpy"
# Cross-shell prompt for astronauts
brew "starship"
# User interface to the TELNET protocol
brew "telnet"
# Programmatically correct mistyped console commands
brew "thefuck"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Sends magic packets to wake up network-devices
brew "wakeonlan"
# Internet file retriever
brew "wget"
# UNIX shell (command interpreter)
brew "zsh"
# Cloudflare Warp
brew "cloudflare/cloudflare/warp", link: false
# A simple terminal UI for git commands, written in Go
brew "jesseduffield/lazygit/lazygit"
# Python cleanup script for macOS
brew "mac-cleanup/mac-cleanup-py/mac-cleanup-py"
# Library to build personalized AI powered by what you've seen, said, or heard.
brew "mediar-ai/screenpipe/screenpipe"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Command-line interface for 1Password
cask "1password-cli"
cask "account-switcher"
# Enable Windows-like alt-tab
cask "alt-tab"
# Transfer files from and to an Android smartphone
cask "android-file-transfer"
# Android SDK component
cask "android-platform-tools"
# Platform for API documentation, debugging, Mock and testing
cask "apipost"
# Application uninstaller
cask "appcleaner"
# User-friendly GUI app for Homebrew
cask "applite"
# Chromium based browser
cask "arc"
# Alternative GUI for Time Machine
cask "backuploupe"
# Menu bar icon organiser
cask "bartender"
# iOS device backup software
cask "bbackupp"
# Rule-based custom proxy with GUI based on clash
cask "clashx-pro"
# Universal database tool and SQL client
cask "dbeaver-community"
# Voice and text chat software
cask "discord"
# Dictionary and translator app
cask "easydict"
# Status monitoring
cask "eul"
# Web browser
cask "firefox"
cask "font-cascadia-mono"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-monaspace"
cask "font-roboto-mono-nerd-font"
cask "font-sauce-code-pro-nerd-font"
# SFMono with Nerd Font Glyphs and Fira Code Ligatures
cask "font-sf-mono-nerd-font-ligaturized"
cask "font-source-code-pro"
cask "font-victor-mono-nerd-font"
# GIT client
cask "fork"
# Git client for simultaneous branches on top of your existing workflow
cask "gitbutler"
# Web browser
cask "google-chrome"
# Graphically shows disk usage within a file system
cask "grandperspective"
# Tool to set light or dark appearance on a per-app basis
cask "gray"
# A Free, Modern Toolbox Built for Developers.
cask "he3"
# Terminal built on web technologies
cask "hyper"
# Free and open-source media player
cask "iina"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Menu bar calendar
cask "itsycal"
# Menu bar manager
cask "jordanbaird-ice"
# Keyboard customiser
cask "karabiner-elements"
# File archiver
cask "keka"
# Helper application for the Keka file archiver
cask "kekaexternalhelper"
# Switch input method per application
cask "keyboardholder"
# Utility that shows the latest app updates
cask "latest"
# Software for Logitech devices
cask "logi-options+"
# Change the style of the Apple logo in macOS menu bar.
cask "logoer"
# Window manager
cask "loop"
# Open-source firewall to block unknown outgoing connections
cask "lulu"
# Track and update to the latest versions of installed software
cask "macupdater"
# Remote desktop client
cask "microsoft-remote-desktop"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# GameStream client
cask "moonlight"
# Smooths scrolling and set mouse scroll directions independently
cask "mos"
# Open-source download manager
cask "motrix"
# Music streaming platform
cask "neteasemusic"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# App to write, plan, collaborate, and get organised
cask "notion"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# System and utility switches
cask "only-switch"
# Replacement for Docker Desktop
cask "orbstack"
# Remote desktop
cask "parsec"
# Utility to uninstall apps and remove leftover files from old/uninstalled apps
cask "pearcleaner"
# Tool for uploading images
cask "picgo"
# Sideload iOS apps and games
cask "playcover-community"
# Quick Look plug-in that renders source code with syntax highlighting
cask "qlcolorcode"
# Display image info and preview unsupported formats in QuickLook
cask "qlimagesize"
# Quick Look generator for Markdown files
cask "qlmarkdown"
# Quick Look plugin for plaintext files without an extension
cask "qlstephen"
# Thumbnails, static previews, cover art and metadata for video files
cask "qlvideo"
# Chinese music streaming application
cask "qqmusic"
# Quick Look plugin for JSON files
cask "quicklook-json"
# Quick Look generator for Adobe Swatch Exchange files
cask "quicklookase"
# A lightweight and high-performance screen recorder for macOS.
cask "quickrecorder"
# Control your tools with a few keystrokes
cask "raycast"
# Snip or pin screenshots
cask "snipaste"
# Open source cross-platform file explorer
cask "spacedrive"
# Tool for managing the OpenSSH ssh client configuration file
cask "ssh-config-editor"
# System monitor for the menu bar
cask "stats"
# Network toolbox
cask "surge"
# App to switch hosts
cask "switchhosts"
# Terminal emulator, SSH and serial client
cask "tabby"
# Messaging app with a focus on speed and security
cask "telegram"
# Finder extension for opening a terminal from the current directory
cask "termhere"
# Remote control software
cask "todesk"
# Utility to hide the notch
cask "topnotch"
# Virtual machines UI using QEMU
cask "utm"
# Plug-in productivity tool set
cask "utools"
# Open-source code editor
cask "visual-studio-code"
# Remote desktop application focusing on security
cask "vnc-viewer"
# Rust-based terminal
cask "warp"
# Quick Look plugin for webp files
cask "webpquicklook"
# Free messaging and calling application
cask "wechat"
# Wine wrapper built with SwiftUI
cask "whisky"
# All-in-one office service platform in Chinese
cask "wpsoffice-cn"
# Third-party NetEase cloud player
cask "yesplaymusic"
# YouTube Music Desktop App
cask "youtube-music"
# Multiplayer code editor
cask "zed"
