tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
# Shell extension to jump to frequently used directories
brew "autojump"
# Fast and simple Node.js version manager
brew "fnm"
# User interface to the TELNET protocol
brew "telnet"
# Internet file retriever
brew "wget"
# Command-line helper for the 1Password password manager
cask "1password-cli"
# Application uninstaller
cask "appcleaner"
# Rule-based custom proxy with GUI based on clash
cask "clashx-pro"
# Voice and text chat software
cask "discord"
# Typeface made for developers
cask "font-jetbrains-mono"
# GIT client
cask "fork"
# Tool to set light or dark appearance on a per-app basis
cask "gray"
# Free and open-source media player
cask "iina"
# File archiver
cask "keka"
# Switch input method per application
cask "keyboardholder"
# Simple and elegant markdown editor
cask "mark-text"
# Tool to control external monitor brightness & volume
cask "monitorcontrol"
# Smooths scrolling and set mouse scroll directions independently
cask "mos"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# App to write, plan, collaborate, and get organized
cask "notion"
# QuickLook plug-in that renders source code with syntax highlighting
cask "qlcolorcode"
# Display image info and preview unsupported formats in QuickLook
cask "qlimagesize"
# QuickLook generator for Markdown files
cask "qlmarkdown"
# QuickLook plugin for plaintext files without an extension
cask "qlstephen"
# QuickLook generator for video files
cask "qlvideo"
# QuickLook plugin for JSON files
cask "quicklook-json"
# QuickLook generator for Adobe Swatch Exchange files
cask "quicklookase"
# Control your tools with a few keystrokes
cask "raycast"
# Music streaming service
cask "spotify"
# System monitor for the menu bar
cask "stats"
# App to switch hosts
cask "switchhosts"
# Terminal emulator, SSH and serial client
cask "tabby"
# Remote desktop application focusing on security
cask "vnc-viewer"
# Rust-based terminal
cask "warp"
cask "webpquicklook"
# Third-party NetEase cloud player
cask "yesplaymusic"
