name: Ubuntu

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: curl -o- https://raw.githubusercontent.com/GodD6366/dotfiles/main/_install/wsl.sh | bash
